import { boolean, integer, pgTable, text, timestamp } from 'drizzle-orm/pg-core'

export const user = pgTable('user', { id: text('id').primaryKey(), name: text('name').notNull(), email: text('email').notNull().unique(), emailVerified: boolean('emailVerified').default(false).notNull(), image: text('image'), createdAt: timestamp('createdAt').defaultNow().notNull(), updatedAt: timestamp('updatedAt').defaultNow().notNull() })
export const session = pgTable('session', { id: text('id').primaryKey(), expiresAt: timestamp('expiresAt').notNull(), token: text('token').notNull().unique(), createdAt: timestamp('createdAt').defaultNow().notNull(), updatedAt: timestamp('updatedAt').defaultNow().notNull(), ipAddress: text('ipAddress'), userAgent: text('userAgent'), userId: text('userId').notNull() })
export const account = pgTable('account', { id: text('id').primaryKey(), accountId: text('accountId').notNull(), providerId: text('providerId').notNull(), userId: text('userId').notNull(), accessToken: text('accessToken'), refreshToken: text('refreshToken'), idToken: text('idToken'), accessTokenExpiresAt: timestamp('accessTokenExpiresAt'), refreshTokenExpiresAt: timestamp('refreshTokenExpiresAt'), scope: text('scope'), password: text('password'), createdAt: timestamp('createdAt').defaultNow().notNull(), updatedAt: timestamp('updatedAt').defaultNow().notNull() })
export const verification = pgTable('verification', { id: text('id').primaryKey(), identifier: text('identifier').notNull(), value: text('value').notNull(), expiresAt: timestamp('expiresAt').notNull(), createdAt: timestamp('createdAt').defaultNow().notNull(), updatedAt: timestamp('updatedAt').defaultNow().notNull() })
export const inventoryItem = pgTable('inventory_item', { id: text('id').primaryKey(), branchId: text('branch_id').notNull(), name: text('name').notNull(), unit: text('unit').notNull(), stock: integer('stock').default(0).notNull(), minimumStock: integer('minimum_stock').default(0).notNull(), costCents: integer('cost_cents').default(0).notNull(), createdAt: timestamp('created_at').defaultNow().notNull() })
export const sale = pgTable('sale', { id: text('id').primaryKey(), branchId: text('branch_id').notNull(), totalCents: integer('total_cents').notNull(), paymentMethod: text('payment_method').notNull(), status: text('status').default('paid').notNull(), createdAt: timestamp('created_at').defaultNow().notNull() })

export const restaurant = pgTable('restaurant', { id: text('id').primaryKey(), name: text('name').notNull(), slug: text('slug').notNull().unique(), logoUrl: text('logo_url'), primaryColor: text('primary_color').default('#c86b4a').notNull(), secondaryColor: text('secondary_color'), currency: text('currency').default('MXN').notNull(), taxRate: integer('tax_rate').default(1600).notNull(), taxId: text('tax_id'), createdAt: timestamp('created_at').defaultNow().notNull(), updatedAt: timestamp('updated_at').defaultNow().notNull() })
export const restaurantBranch = pgTable('restaurant_branch', { id: text('id').primaryKey(), restaurantId: text('restaurant_id').notNull(), name: text('name').notNull(), address: text('address'), isActive: boolean('is_active').default(true).notNull(), createdAt: timestamp('created_at').defaultNow().notNull() })
export const restaurantMembership = pgTable('restaurant_membership', { id: text('id').primaryKey(), userId: text('user_id').notNull(), restaurantId: text('restaurant_id').notNull(), role: text('role').default('staff').notNull(), branchId: text('branch_id'), isActive: boolean('is_active').default(true).notNull(), createdAt: timestamp('created_at').defaultNow().notNull() })
export const menuCategory = pgTable('menu_category', { id: text('id').primaryKey(), restaurantId: text('restaurant_id').notNull(), name: text('name').notNull(), sortOrder: integer('sort_order').default(0).notNull(), isActive: boolean('is_active').default(true).notNull(), createdAt: timestamp('created_at').defaultNow().notNull() })
export const menuProduct = pgTable('menu_product', { id: text('id').primaryKey(), restaurantId: text('restaurant_id').notNull(), categoryId: text('category_id'), name: text('name').notNull(), description: text('description'), priceCents: integer('price_cents').default(0).notNull(), imageUrl: text('image_url'), isAvailable: boolean('is_available').default(true).notNull(), createdAt: timestamp('created_at').defaultNow().notNull(), updatedAt: timestamp('updated_at').defaultNow().notNull() })
export const restaurantSettings = pgTable('restaurant_settings', { restaurantId: text('restaurant_id').primaryKey(), theme: text('theme').default('terracotta').notNull(), accentColor: text('accent_color').default('#c86b4a').notNull(), logoUrl: text('logo_url'), receiptFooter: text('receipt_footer'), updatedAt: timestamp('updated_at').defaultNow().notNull() })
